#!/bin/bash
set -e

[ -w /usr/local/lib ] || { echo "Can't write to /usr/local/lib"; exit 1; }
[ -w /usr/local/bin ] || { echo "Can't write to /usr/local/bin"; exit 1; }

cp -r "$(dirname "$0")" /usr/local/lib/llm-janitor
ln -sf /usr/local/lib/llm-janitor/llm-janitor /usr/local/bin/llm-janitor

echo "Deployed"
